version: "3.9"

services:
  db:
    env_file: .env
    image: postgres:14-alpine
    container_name: fequa-db
    volumes:
      - data_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
     - default

volumes:
  data_db: